dist: trusty

language: csharp
solution: csharp.sln
mono: none
dotnet: 2.0.0

script:
  - dotnet publish --runtime linux-x64
  - ./functional_tests/test.sh ~/.cargo/bin/bionitio-rs
  - ./.travis/unit-test.sh

